### ISSUE TITLE
Camera Intrinsics

### ISSUE THREAD

**Issue by Xonxt** [NeLy-EPFL/DeepFly3D#34]
Hello,

looking through the code and having made some tests, I can see where the **Rotation** and **Translation** matrices are calculated and the written into each `Camera` object (calling the `set_rvec()` and `set_tvec()` methods), but I was unable to find any instance where the intrinsics of the cameras (the `intr` and `distort` matrices) are calculated. 

And in fact, they just remain as default values. Except for the "fly" example, where the "default" camera intrinsics are read from a pickled file.

Am I to understand that the camera intrinsics are not calculated by the framework and need to be provided for each camera manually before the start of the calibration? Or am I missing something?

**Comment by semihgunel** [comment]
Hi,
The intrinsic matrix is not calculated but set at the start. It is because the majority of the cameras come with known intrinsic values, so we don't need to optimize for them. 

you can see/change the default values here: https://github.com/NeLy-EPFL/DeepFly3D/blob/974f839e224a41e7c5774e2effddf8ff763da88a/deepfly/Camera.py#L29

or, if you are loading them from the picked file, then you need to change them there.

> Am I to understand that the camera intrinsics are not calculated by the framework and need to be provided for each camera manually before the start of the calibration? Or am I missing something?

Yes, you are right. the intrinsic values should be provided before the start of the calibration.
